[2022-10-02 03:44:17,990] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: docker_operator_demo.docker_command_sleep scheduled__2022-10-02T02:05:00+00:00 [queued]>
[2022-10-02 03:44:18,059] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: docker_operator_demo.docker_command_sleep scheduled__2022-10-02T02:05:00+00:00 [queued]>
[2022-10-02 03:44:18,063] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-10-02 03:44:18,064] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-10-02 03:44:18,066] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-10-02 03:44:18,139] {taskinstance.py:1259} INFO - Executing <Task(DockerOperator): docker_command_sleep> on 2022-10-02 02:05:00+00:00
[2022-10-02 03:44:18,167] {standard_task_runner.py:52} INFO - Started process 878 to run task
[2022-10-02 03:44:18,179] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'docker_operator_demo', 'docker_command_sleep', 'scheduled__2022-10-02T02:05:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/sample_dag.py', '--cfg-path', '/tmp/tmp12w7gpnt', '--error-file', '/tmp/tmp2z7v261f']
[2022-10-02 03:44:18,185] {standard_task_runner.py:77} INFO - Job 19: Subtask docker_command_sleep
[2022-10-02 03:44:18,439] {logging_mixin.py:109} INFO - Running <TaskInstance: docker_operator_demo.docker_command_sleep scheduled__2022-10-02T02:05:00+00:00 [running]> on host 336e822c453c
[2022-10-02 03:44:18,742] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=docker_operator_demo
AIRFLOW_CTX_TASK_ID=docker_command_sleep
AIRFLOW_CTX_EXECUTION_DATE=2022-10-02T02:05:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-02T02:05:00+00:00
[2022-10-02 03:44:18,891] {docker.py:258} INFO - Starting docker container from image alpine:latest
[2022-10-02 03:44:18,999] {docker.py:269} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2022-10-02 03:44:19,615] {docker.py:320} INFO - hello
[2022-10-02 03:44:19,862] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=docker_operator_demo, task_id=docker_command_sleep, execution_date=20221002T020500, start_date=20221002T034417, end_date=20221002T034419
[2022-10-02 03:44:19,979] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-10-02 03:44:20,153] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
